deploy_to_heroku:
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
  - docker:dind
  script:
    - git lfs pull
    - docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
    - docker build -t registry.heroku.com/background-removal/web .
    - docker push registry.heroku.com/background-removal/web