deploy_to_heroku:
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay
  services:
  - docker:dind
  before_script:
    # Install git-lfs
    - apk add openssl git-core --update-cache
    - wget -qO- https://github.com/git-lfs/git-lfs/releases/download/v2.1.1/git-lfs-linux-amd64-2.1.1.tar.gz | tar xz
    - mv git-lfs-*/git-lfs /usr/bin/ && rm -rf git-lfs-* && git lfs install && git lfs pull
  script:
    - apk add git git-lfs --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/
    - git lfs pull
    - docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
    - docker build -t registry.heroku.com/background-removal/web .
    - docker push registry.heroku.com/background-removal/web